// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcJEJkJWM1g_37HQhSCWUM3RpHaDvgOII',
    appId: '1:156644037566:web:e7929054577bb5b6471fef',
    messagingSenderId: '156644037566',
    projectId: 'hide-app-f0e98',
    authDomain: 'hide-app-f0e98.firebaseapp.com',
    storageBucket: 'hide-app-f0e98.firebasestorage.app',
    measurementId: 'G-2ZWJMZMJ64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgB9ZKuUIwfFJjhPxRiS3IibZfGUY1bEk',
    appId: '1:156644037566:android:4c2f2a2f3b50966e471fef',
    messagingSenderId: '156644037566',
    projectId: 'hide-app-f0e98',
    storageBucket: 'hide-app-f0e98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxEcYgl7rfrCUfGa2VqiHUr9QSDDQ7BSA',
    appId: '1:156644037566:ios:27c0565083caa780471fef',
    messagingSenderId: '156644037566',
    projectId: 'hide-app-f0e98',
    storageBucket: 'hide-app-f0e98.firebasestorage.app',
    iosBundleId: 'com.example.hideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxEcYgl7rfrCUfGa2VqiHUr9QSDDQ7BSA',
    appId: '1:156644037566:ios:27c0565083caa780471fef',
    messagingSenderId: '156644037566',
    projectId: 'hide-app-f0e98',
    storageBucket: 'hide-app-f0e98.firebasestorage.app',
    iosBundleId: 'com.example.hideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcJEJkJWM1g_37HQhSCWUM3RpHaDvgOII',
    appId: '1:156644037566:web:0e9410d21d523a09471fef',
    messagingSenderId: '156644037566',
    projectId: 'hide-app-f0e98',
    authDomain: 'hide-app-f0e98.firebaseapp.com',
    storageBucket: 'hide-app-f0e98.firebasestorage.app',
    measurementId: 'G-HNL5F8MW9V',
  );
}
